# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BuildTestMainWindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMdiArea, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QToolBar,
    QVBoxLayout, QWidget)
# import resources_rc

class Ui_BuidTestMainWindow(object):
    def setupUi(self, BuidTestMainWindow):
        if not BuidTestMainWindow.objectName():
            BuidTestMainWindow.setObjectName(u"BuidTestMainWindow")
        BuidTestMainWindow.setEnabled(True)
        BuidTestMainWindow.resize(1080, 719)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(BuidTestMainWindow.sizePolicy().hasHeightForWidth())
        BuidTestMainWindow.setSizePolicy(sizePolicy)
        BuidTestMainWindow.setSizeIncrement(QSize(0, 0))
        BuidTestMainWindow.setAutoFillBackground(True)
        BuidTestMainWindow.setToolButtonStyle(Qt.ToolButtonIconOnly)
        BuidTestMainWindow.setDockOptions(QMainWindow.AllowTabbedDocks|QMainWindow.AnimatedDocks)
        self.actionUndo = QAction(BuidTestMainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        self.actionSetting = QAction(BuidTestMainWindow)
        self.actionSetting.setObjectName(u"actionSetting")
        self.actionAbout = QAction(BuidTestMainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionOpen = QAction(BuidTestMainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon = QIcon()
        icon.addFile(u":/icons/icons/open.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon)
        self.actionSave = QAction(BuidTestMainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave.setCheckable(True)
        icon1 = QIcon()
        icon1.addFile(u":/icons/icons/saveColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave_all = QAction(BuidTestMainWindow)
        self.actionSave_all.setObjectName(u"actionSave_all")
        self.actionSave_AS = QAction(BuidTestMainWindow)
        self.actionSave_AS.setObjectName(u"actionSave_AS")
        self.actionNew = QAction(BuidTestMainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon2 = QIcon()
        icon2.addFile(u":/icons/icons/new.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionCut = QAction(BuidTestMainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon3 = QIcon()
        icon3.addFile(u":/icons/icons/cut.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCut.setIcon(icon3)
        self.actionCopy = QAction(BuidTestMainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon4 = QIcon()
        icon4.addFile(u":/icons/icons/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionInsertStep = QAction(BuidTestMainWindow)
        self.actionInsertStep.setObjectName(u"actionInsertStep")
        self.actionDeleteStep = QAction(BuidTestMainWindow)
        self.actionDeleteStep.setObjectName(u"actionDeleteStep")
        self.actionClearCell = QAction(BuidTestMainWindow)
        self.actionClearCell.setObjectName(u"actionClearCell")
        self.actionPaste = QAction(BuidTestMainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon5 = QIcon()
        icon5.addFile(u":/icons/icons/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPaste.setIcon(icon5)
        self.actionViewMode = QAction(BuidTestMainWindow)
        self.actionViewMode.setObjectName(u"actionViewMode")
        self.actionViewMode.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/icons/icons/windowMode.png", QSize(), QIcon.Normal, QIcon.Off)
        icon6.addFile(u":/icons/icons/tabMode.png", QSize(), QIcon.Disabled, QIcon.Off)
        icon6.addFile(u":/icons/icons/tabMode.png", QSize(), QIcon.Active, QIcon.On)
        self.actionViewMode.setIcon(icon6)
        self.actionCascade = QAction(BuidTestMainWindow)
        self.actionCascade.setObjectName(u"actionCascade")
        icon7 = QIcon()
        icon7.addFile(u":/icons/icons/cascade.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCascade.setIcon(icon7)
        self.actionTile = QAction(BuidTestMainWindow)
        self.actionTile.setObjectName(u"actionTile")
        icon8 = QIcon()
        icon8.addFile(u":/icons/icons/tile.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionTile.setIcon(icon8)
        self.centralwidget = QWidget(BuidTestMainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.mdiArea = QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(u"mdiArea")
        sizePolicy.setHeightForWidth(self.mdiArea.sizePolicy().hasHeightForWidth())
        self.mdiArea.setSizePolicy(sizePolicy)

        self.verticalLayout.addWidget(self.mdiArea)

        BuidTestMainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QToolBar(BuidTestMainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setEnabled(True)
        BuidTestMainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QStatusBar(BuidTestMainWindow)
        self.statusBar.setObjectName(u"statusBar")
        BuidTestMainWindow.setStatusBar(self.statusBar)
        self.menuBar = QMenuBar(BuidTestMainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1080, 22))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuOptions = QMenu(self.menuBar)
        self.menuOptions.setObjectName(u"menuOptions")
        self.menuWindow = QMenu(self.menuBar)
        self.menuWindow.setObjectName(u"menuWindow")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        BuidTestMainWindow.setMenuBar(self.menuBar)

        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_all)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.actionCopy)
        self.toolBar.addAction(self.actionPaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionViewMode)
        self.toolBar.addAction(self.actionCascade)
        self.toolBar.addAction(self.actionTile)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_all)
        self.menuFile.addAction(self.actionSave_AS)
        self.menuFile.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionInsertStep)
        self.menuEdit.addAction(self.actionDeleteStep)
        self.menuEdit.addAction(self.actionClearCell)
        self.menuOptions.addAction(self.actionSetting)
        self.menuWindow.addAction(self.actionViewMode)
        self.menuWindow.addAction(self.actionCascade)
        self.menuWindow.addAction(self.actionTile)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(BuidTestMainWindow)

        QMetaObject.connectSlotsByName(BuidTestMainWindow)
    # setupUi

    def retranslateUi(self, BuidTestMainWindow):
        BuidTestMainWindow.setWindowTitle(QCoreApplication.translate("BuidTestMainWindow", u"BuidTest", None))
        self.actionUndo.setText(QCoreApplication.translate("BuidTestMainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("BuidTestMainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionSetting.setText(QCoreApplication.translate("BuidTestMainWindow", u"Setting", None))
        self.actionAbout.setText(QCoreApplication.translate("BuidTestMainWindow", u"about", None))
        self.actionOpen.setText(QCoreApplication.translate("BuidTestMainWindow", u"Open...", None))
        self.actionSave.setText(QCoreApplication.translate("BuidTestMainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("BuidTestMainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_all.setText(QCoreApplication.translate("BuidTestMainWindow", u"Save All", None))
        self.actionSave_AS.setText(QCoreApplication.translate("BuidTestMainWindow", u"Save AS...", None))
        self.actionNew.setText(QCoreApplication.translate("BuidTestMainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("BuidTestMainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("BuidTestMainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("BuidTestMainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("BuidTestMainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("BuidTestMainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionInsertStep.setText(QCoreApplication.translate("BuidTestMainWindow", u"Insert Step", None))
        self.actionDeleteStep.setText(QCoreApplication.translate("BuidTestMainWindow", u"Delete Step", None))
        self.actionClearCell.setText(QCoreApplication.translate("BuidTestMainWindow", u"Clear Cell", None))
        self.actionPaste.setText(QCoreApplication.translate("BuidTestMainWindow", u"Paste", None))
#if QT_CONFIG(tooltip)
        self.actionPaste.setToolTip(QCoreApplication.translate("BuidTestMainWindow", u"\ubd99\uc5ec\ub123\uae30", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("BuidTestMainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionViewMode.setText(QCoreApplication.translate("BuidTestMainWindow", u"WindowMode", None))
        self.actionCascade.setText(QCoreApplication.translate("BuidTestMainWindow", u"Cascade", None))
        self.actionTile.setText(QCoreApplication.translate("BuidTestMainWindow", u"Tile", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("BuidTestMainWindow", u"toolBar", None))
        self.menuFile.setTitle(QCoreApplication.translate("BuidTestMainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("BuidTestMainWindow", u"Edit", None))
        self.menuOptions.setTitle(QCoreApplication.translate("BuidTestMainWindow", u"Options", None))
        self.menuWindow.setTitle(QCoreApplication.translate("BuidTestMainWindow", u"Window", None))
        self.menuHelp.setTitle(QCoreApplication.translate("BuidTestMainWindow", u"Help", None))
    # retranslateUi

